---
# yum repoistory create
- name: Create working directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /mnt/cdrom
    - /root/src
    - /var/www/html/repo

- name: Create mount point
  file:
    path: /mnt/cdrom
    state: directory

# CLI install
- name: download openshift-installer /root/src
  ansible.builtin.get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.19/openshift-install-linux-4.19.14.tar.gz"
    dest: "/root/src/openshift-install-linux-4.19.14.tar.gz"
    mode: "0644"
  register: download_result
  ignore_errors: true

- name: "Show openshift-installer /root/src"
  ansible.builtin.debug:
    msg:
      - "openshift-installer file downloaded"
      - "URL: {{ download_result.url | default('Download skipped or failed') }}"
      - "Path: {{ download_result.dest | default('N/A') }}"
  when: download_result is defined

- name: Sleep 5 seconds before next download
  ansible.builtin.wait_for:
    timeout: 5

- name: download openshif-cli /root/src
  ansible.builtin.get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.19/openshift-client-linux.tar.gz"
    dest: "/root/src/openshift-client-linux.tar.gz"
    mode: "0644"
  register: download_result
  ignore_errors: true

- name: "Show openshift-client /root/src"
  ansible.builtin.debug:
    msg:
      - "openshift-client file downloaded"
      - "URL: {{ download_result.url | default('Download skipped or failed') }}"
      - "Path: {{ download_result.dest | default('N/A') }}"
  when: download_result is defined

- name: Sleep 5 seconds before next download
  ansible.builtin.wait_for:
    timeout: 5

- name: download openshif-mirror /root/src
  ansible.builtin.get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable-4.19/oc-mirror.tar.gz"
    dest: "/root/src/oc-mirror.tar.gz"
    mode: "0644"
  register: download_result
  ignore_errors: true

- name: "Show openshift-mirror /root/src"
  ansible.builtin.debug:
    msg:
      - "openshift-mirror file downloaded"
      - "URL: {{ download_result.url | default('Download skipped or failed') }}"
      - "Path: {{ download_result.dest | default('N/A') }}"
  when: download_result is defined

- name: Sleep 5 seconds before next download
  ansible.builtin.wait_for:
    timeout: 5

- name: unarchive openshift-installer file 
  unarchive:
    src: "/root/src/openshift-install-linux-4.19.14.tar.gz"
    dest: "/root/src/"
    remote_src: True
  become: True  

- name: unarchive openshift-client file 
  unarchive:
    src: "/root/src/openshift-client-linux.tar.gz"
    dest: "/root/src/"
    remote_src: True
  become: True 

- name: unarchive oc-mirror file 
  unarchive:
    src: "/root/src/oc-mirror.tar.gz"
    dest: "/root/src/"
    remote_src: True
  become: True 

- name: openshift-installer to local directory
  command: cp -a /root/src/openshift-install /usr/bin/

- name: openshift-client to local directory
  command: cp -a /root/src/oc /usr/bin/

- name: kubernetes-client to local directory
  command: cp -a /root/src/kubectl /usr/bin/

- name: oc-mirror to local directory
  command: cp -a /root/src/oc-mirror /usr/bin/
- name: oc-mirror to local directory
  command: chmod 711 /usr/bin/oc-mirror
 
# CD-Rom Copy
- name: Mount CD-ROM
  mount:
    path: /mnt/cdrom
    src: /dev/cdrom
    fstype: iso9660
    state: mounted

- name: Sleep 10 seconds after mounting CD-ROM
  ansible.builtin.wait_for:
    timeout: 10

- name: Install createrepo_c packages from AppStream
  ansible.builtin.dnf:
    name:
    - /mnt/cdrom/AppStream/Packages/createrepo_c-libs-0.20.1-2.el9.x86_64.rpm
    - /mnt/cdrom/AppStream/Packages/python3-createrepo_c-0.20.1-2.el9.x86_64.rpm
    - /mnt/cdrom/AppStream/Packages/createrepo_c-0.20.1-2.el9.x86_64.rpm
    state: present

- name: Copy CD-ROM contents to local directory
  command: cp -a /mnt/cdrom/. /var/www/html/repo/
  args:
    creates: /var/www/html/repo/.discinfo

#- name: Unmount CD-ROM
#  mount:
#    path: /mnt/cdrom
#    state: unmounted

- name: Generate repository metadata
  command: createrepo_c /var/www/html/repo/
  args:
    creates: "/var/www/html/repo/repodata"

# HTTPD isntall
- name: httpd install 
  ansible.builtin.dnf:
    name: httpd
    state: present 

- name: Sleep 3 seconds after starting httpd
  ansible.builtin.wait_for:
    timeout: 3

- name: httpd start 
  shell: systemctl start httpd && systemctl enable httpd

# image registry
- name: podman install 
  ansible.builtin.dnf:
    name: podman
    state: present 

- name: Sleep 3 seconds after starting httpd
  ansible.builtin.wait_for:
    timeout: 3

- name: Task Completed
  debug:
    msg: "✅ Bastion Initialization Completed Successfully"