---
- name: download openshif-cli /root/src
  ansible.builtin.get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/latest/rhcos-4.19.10-x86_64-vmware.x86_64.ova"
    dest: "/root/src/rhcos-4.19.10-x86_64-vmware.x86_64.ova"
    mode: "0644"
  register: download_result
  ignore_errors: true

- name: "Show OVA file download result"
  ansible.builtin.debug:
    msg:
      - "RHCOS OVA file downloaded"
      - "URL: {{ download_result.url | default('Download skipped or failed') }}"
      - "Path: {{ download_result.dest | default('N/A') }}"
  when: download_result is defined

    
- name: "deploy rhcos ova"
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ vmfolder }}"
    name: "{{ templateCoreOS }}"
    template: "{{ templateCoreOS }}"   
    networks: 
      - name:  "{{ vcenter_network }}"
    ovf_path: /root/src/rhcos-4.19.10-x86_64-vmware.x86_64.ova
    state: poweredoff

- name: "Template Deployment Completed"
  ansible.builtin.debug:
    msg:
      - "RHCOS Template '{{ templateCoreOS }}' successfully registered in vCenter."
      - "Datacenter: {{ vcenter_datacenter }}"
      - "Cluster: {{ vcenter_cluster }}"
      - "Datastore: {{ vcenter_datastore }}"