---
- name: Power On VM after clone
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ vm_name }}"
    state: poweredon
  delegate_to: localhost