---
- name: Power on all masters
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ hostvars[item].vm_name | default(item) }}"
    state: poweredon
  loop: "{{ groups['master'] }}"

- name: Power on all workers
  community.vmware.vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ hostvars[item].vm_name | default(item) }}"
    state: poweredon
  loop: "{{ groups['worker'] }}"
